[tool.black]
line-length = 88
target-version = ["py310"]

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503,E501"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "migrations"
]

[tool.isort]
profile = "black"
line_length = 88