name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy pytest
        pip install -r requirements.txt

    - name: Format with Black
      run: black .

    - name: Run flake8
      run: flake8 . --max-line-length=88

    - name: Check imports with isort
      run: isort --check .

    - name: Type checking with mypy
      run: mypy --ignore-missing-imports .

    - name: Run tests
      run: pytest -v