name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy pytest
        pip install flask==2.0.1 flask-sqlalchemy==2.5.1

    - name: Run linters
      run: |
        flake8 . --max-line-length=88
        black --check --line-length 88 .
        isort --check .
        mypy --ignore-missing-imports .

    - name: Run tests
      run: |
        pytest -v