name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -e .
        pip install black flake8 isort mypy pytest

    - name: Run formatters and linters
      run: |
        black .
        flake8 .
        isort .
        mypy .

    - name: Run tests
      run: pytest -v